# Site settings
title: Dev Robin Blog
email: robinseojun0625@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swjun08.github.io" # the base hostname & protocol for your site
#twitter_username: your-twitter-username
github_username:  swjun08

# Build settings
remote_theme: ngzhio/jekyll-theme-hamilton
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional settings
author:
  name: Seojun Park
  #avatar: /path/to/avatar.png
  #bio: "Your bio"
  location: Your Location
  email: your-email@example.com
  links:
    #- title: Twitter
     # url: https://twitter.com/your-twitter-username
      #icon: fab fa-twitter
    - title: GitHub
      url: https://github.com/swjun08
      icon: fab fa-github

paginate: 5
paginate_path: "/page/:num/"
timezone: America/New_York # Set your timezone

# Customization
skin: daylight
lang: en
date_format: "%b %-d, %Y"
subscribe: true

# SEO and Analytics
google_analytics: UA-XXXXXXXXX-X
disqus: swjun08

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Categories
    url: /categories/
  - title: Tags
    url: /tags/
  - title: Contact
    url: /contact/

# Social Links
social:
  #- title: Twitter
   # url: https://twitter.com/your-twitter-username
    #icon: fab fa-twitter
  - title: GitHub
    url: https://github.com/swjun08
    icon: fab fa-github
  #- title: LinkedIn
   # url: https://www.linkedin.com/in/your-linkedin-username
   # icon: fab fa-linkedin

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
